name: CI Terraform Docs 
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@main
      with:
        find-dir: find -type d -name "mo*"
        output-file: README.md
        output-method: inject
        git-push: "true"
        template: |-
          <!-- BEGIN_TF_DOCS -->
          #### Table of Contents
          1. [Usage](#usage)
          2. [Requirements](#requirements)
          3. [Providers](#Providers)
          4. [Inputs](#inputs)
          5. [Outputs](#outputs)
          
          ## Usage
          {{ .Content }}
          <!-- END_TF_DOCS -->
        indention: 3
