name: Auto build terraform docs and push changes back to PR
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: CI Terraform Docs
      uses: terraform-docs/gh-actions@main
      with:
        find-dir: module
        output-file: README.md
        output-method: inject
        git-push: "true"
        template: |-
          <!-- BEGIN_TF_DOCS -->
          #### Table of Contents
          1. [Usage](#usage)
          2. [Requirements](#requirements)
          3. [Providers](#Providers)
          4. [Inputs](#inputs)
          5. [Outputs](#outputs)
          
          ## Usage
          <!-- END_TF_DOCS -->
        indention: 3
